# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kq.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import datetime
from PyQt5 import QtCore, QtWidgets
import pymysql
from PyQt5.QtWidgets import QTableWidgetItem, QAbstractItemView, QMessageBox
import csv

db = pymysql.connect(host='127.0.0.1', port=3306, user='root', password='Ntss2000')
cursor = db.cursor()
sql = "select * from employee.today"
cursor.execute(sql)
data = cursor.fetchall()


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(120, 30, 600, 450))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(len(data))
        self.tableWidget.setHorizontalHeaderLabels(["工号", "姓名", "考勤时间", '是否迟到'])
        self.tableWidget.setColumnWidth(0, 150)
        self.tableWidget.setColumnWidth(1, 100)
        self.tableWidget.setColumnWidth(2, 200)
        self.tableWidget.setColumnWidth(3, 150)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)

        for i in range(len(data)):
            self.tableWidget.setItem(i, 0, QTableWidgetItem(data[i][0]))
            self.tableWidget.setItem(i, 1, QTableWidgetItem(data[i][1]))
            self.tableWidget.setItem(i, 2, QTableWidgetItem(data[i][2]))
            self.tableWidget.setItem(i, 3, QTableWidgetItem(data[i][3]))

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 550, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.refresh)

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 550, 112, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.output)

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 550, 112, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.close)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def refresh(self):
        cursor.execute(sql)
        data = cursor.fetchall()
        print(data)
        for i in range(len(data)):
            self.tableWidget.setItem(i, 0, QTableWidgetItem(data[i][0]))
            self.tableWidget.setItem(i, 1, QTableWidgetItem(data[i][1]))
            self.tableWidget.setItem(i, 2, QTableWidgetItem(data[i][2]))
            self.tableWidget.setItem(i, 3, QTableWidgetItem(data[i][3]))

    def output(self):
        fn = './data/{}.csv'.format(datetime.datetime.now().strftime('%Y%m%d'))
        with open(fn, 'w', encoding='utf8', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(["工号", "姓名", "考勤时间", '是否迟到'])
            writer.writerows(data)
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("导出完成！")
        msg.setWindowTitle("提示")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "刷新"))
        self.pushButton_2.setText(_translate("Dialog", "导出考勤表"))
        self.pushButton_3.setText(_translate("Dialog", "返回"))

