# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kqmsg = QtWidgets.QPushButton(self.centralwidget)
        self.kqmsg.setGeometry(QtCore.QRect(340, 140, 112, 32))
        self.kqmsg.setObjectName("kqmsg")
        self.addmsg = QtWidgets.QPushButton(self.centralwidget)
        self.addmsg.setGeometry(QtCore.QRect(340, 220, 112, 32))
        self.addmsg.setObjectName("addmsg")
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setGeometry(QtCore.QRect(340, 300, 112, 32))
        self.quit.setObjectName("quit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kqmsg.setText(_translate("MainWindow", "考勤信息"))
        self.addmsg.setText(_translate("MainWindow", "信息录入"))
        self.quit.setText(_translate("MainWindow", "退出系统"))
